Fix Color Theme
Sports-day/sports-day-form pull request #21
Opened 2024-04-08 14:59 UTC by Takkun0310

Changing the definition method of color themes and adapting colors to components.

2024-04-08 22:38 UTC, testusuke commented on components/Footer.tsx
> +                            color: 's-lightest.main',
's-lightest'だけでは指定できませんでしたか？

2024-04-08 22:39 UTC, testusuke commented on components/Header.tsx
> +                    color: 's-lightest.main',
同様

2024-04-08 22:41 UTC, testusuke commented on app/login/page.tsx
> +            <Stack height="100vh" justifyContent="center" alignItems="center" spacing="32px">
@1nayu Stack等のspacingはピクセルではなく、MUIに任せるべきですかね？
マージン等に関してはpxでもいいとは考えていますが...

2024-04-08 22:43 UTC, testusuke requested changes
@Takkun0310 
書き方も非常に綺麗になってきてすごいです！

この二つのことが少し気になったので検証か回答お願いします🙏
- `s-lightest.main`を`s-lightest`に省略できないか？
- spacingの再検討(昨日マージンの話かと思ってた...🙇)

2024-04-08 23:59 UTC, Takkun0310 commented
@testusuke
検証 
・colorの定義
　→検証してみたところ、現在のthemeの定義方法ではなぜか'.main'をつけないと反映されませんでした...
・spacingの値の定義
　→時間があるときに統一しときます😎

2024-04-09 02:26 UTC, 1nayu commented on app/login/page.tsx
> +            <Stack height="100vh" justifyContent="center" alignItems="center" spacing="32px">
spacingは個人的には spacing={1}とかでやってます(muiに任せてることになってるのかな)
マージンも大体、単に m=1〜3くらいでしてます

2024-04-09 03:55 UTC, Takkun0310 commented
再検証したところ行けそうな感じでした！
すべて変更しておきます！

2024-04-09 05:20 UTC, testusuke commented
了解です。変更できたらReviewerのところで再度review request投げておいてくださいm(_ _)m

2024-04-09 05:22 UTC, testusuke commented on app/login/page.tsx
> +            <Stack height="100vh" justifyContent="center" alignItems="center" spacing="32px">
なるほど。となると完全にMUIに任せればいいということですか👀
強いな

2024-04-09 07:32 UTC, testusuke approved these changes
LGTM

2024-04-09 07:33 UTC, merged